server:
  port: 4004


spring:
  cloud:
    gateway:
      routes:
        #        http://localhost:4004/auth/login
        #        API GATEWAY -> http://auth-service:4005/login
        - id: auth-service-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        #          Route for /api/patients/** to patient-service
        - id: patient-service-root
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation   # JwtValidationGatewayFilterFactory the starting name has to be same to apply it as filter

        - id: api-docs-patient-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

